export const SET_DEVICE_ID = 'SET_DEVICE_ID';
export const GET_DEVICE_ID = 'GET_DEVICE_ID';

export const SET_SPINNER_VISIBLE = 'SET_SPINNER_VISIBLE';
export const GET_SPINNER_VISIBLE = 'GET_SPINNER_VISIBLE';
