export const SET_DEVICE_ID = 'SET_DEVICE_ID';
export const GET_DEVICE_ID = 'GET_DEVICE_ID';

export const SET_SPINNER_VISIBLE = 'SET_SPINNER_VISIBLE';
export const GET_SPINNER_VISIBLE = 'GET_SPINNER_VISIBLE';

export const SET_END_POINT_ERROR = 'SET_END_POINT_ERROR';
export const GET_END_POINT_ERROR = 'GET_END_POINT_ERROR';
