export const SET_DEVICE_ID = 'SET_DEVICE_ID';
export const GET_DEVICE_ID = 'GET_DEVICE_ID';

export const SET_MOBILE_NUMBER = 'SET_MOBILE_NUMBER';
export const GET_MOBILE_NUMBER = 'GET_MOBILE_NUMBER';

export const SET_SPINNER_VISIBLE = 'SET_SPINNER_VISIBLE';
export const GET_SPINNER_VISIBLE = 'GET_SPINNER_VISIBLE';

export const SET_END_POINT_ERROR = 'SET_END_POINT_ERROR';
export const GET_END_POINT_ERROR = 'GET_END_POINT_ERROR';

export const SET_USER_EMAIL = 'SET_USER_EMAIL';
export const GET_USER_EMAIL = 'GET_USER_EMAIL';

export const SET_USER_ENTERED_NAME = 'SET_USER_ENTERED_NAME';
export const GET_USER_ENTERED_NAME = 'GET_USER_ENTERED_NAME';

export const SET_USER_ENTERED_BIRTH_DATE = 'SET_USER_ENTERED_BIRTH_DATE';
export const GET_USER_ENTERED_BIRTH_DATE = 'GET_USER_ENTERED_BIRTH_DATE';

export const SET_ALERT_BOX_VISIBILITY = 'SET_ALERT_BOX_VISIBILITY';
export const GET_ALERT_BOX_VISIBILITY = 'GET_ALERT_BOX_VISIBILITY';
