const Colors = {
  SCREEN_PRIMARY_BACKGROUND_COLOR: '#272727',
  SCREEN_SECONDARY_BACKGROUND_COLOR: '#012674',
  SCREEN_INACTIVE_COLOR: '#000000',

  PRIMARY_BUTTON_GREEN_COLOR: '#06D30F',
  PRIMARY_BUTTON_BLACK_COLOR: '#303030',

  MODAL_BACKGROUND_COLOR: '#00000060',
  MODAL_FOREGROUND_COLOR: '#363636',

  PRIMARY_TEXT_INPUT_BACKGROUND_COLOR: '#FFFFFF',
  PRIMARY_TEXT_INPUT_BORDER_COLOR: '#EDEDED',
  PRIMARY_TEXT_INPUT_ERROR_BORDER_COLOR: '#FF7171',

  ONBOARDING_PROGRESS_BAR_BACKGROUND_COLOR: '#494949',
  ONBOARDING_PROGRESS_BAR_GREEN: '#06D30F',

  DROPDOWN_LINE_BRAKER_COLOR: '#737373',
  LINE_BRAKER_COLOR: '#555555',
  text: {
    PRIMARY_COLOR: '#FFFFFF',
    SECONDARY_COLOR: '#000000',
    TEXT_INPUT_PLACEHOLDER_COLOR: '#C6C6C6',
    PRIMARY_BUTTON_GREEN_COLOR: '#06D30F',
    PRIMARY_BUTTON_WHITE_COLOR: '#FFFFFF',

    LINK_TEXT_COLOR: '#329DFF',

    WARNING_RED_COLOR: '#FF7171',

    GRAY_TEXT_COLOR: '#BEBEBE',
  },
};

export {Colors};
