const Colors = {
  SCREEN_PRIMARY_BACKGROUND_COLOR: '#272727',
  SCREEN_SECONDARY_BACKGROUND_COLOR: '#012674',

  PRIMARY_BUTTON_GREEN_COLOR: '#06D30F',
  PRIMARY_BUTTON_BLACK_COLOR: '#303030',

  PRIMARY_TEXT_INPUT_BACKGROUND_COLOR: '#FFFFFF',
  PRIMARY_TEXT_INPUT_BORDER_COLOR: '#EDEDED',

  text: {
    PRIMARY_COLOR: '#FFFFFF',
    SECONDARY_COLOR: '#000000',
    TEXT_INPUT_PLACEHOLDER_COLOR: '#C6C6C6',
    PRIMARY_BUTTON_GREEN_COLOR: '#06D30F',
    PRIMARY_BUTTON_WHITE_COLOR: '#FFFFFF',

    WARNING_RED_COLOR: '#FF7171',
  },
};

export {Colors};
