const Colors = {
  SCREEN_PRIMARY_BACKGROUND_COLOR: '#272727',
  SCREEN_SECONDARY_BACKGROUND_COLOR: '#012674',

  PRIMARY_BUTTON_GREEN_COLOR: '#06D30F',
  PRIMARY_BUTTON_BLACK_COLOR: '#303030',

  text: {
    PRIMARY_COLOR: '#FFFFFF',
    PRIMARY_BUTTON_GREEN_COLOR: '#06D30F',
    PRIMARY_BUTTON_WHITE_COLOR: '#FFFFFF',
  },
};

export {Colors};
