export const GET_ADD_LINK_RESPONSE = 'GET_ADD_LINK_RESPONSE';

export const GET_DELETE_LINK_RESPONSE = 'GET_DELETE_LINK_RESPONSE';

export const GET_EDIT_LINK_RESPONSE = 'GET_EDIT_LINK_RESPONSE';

export const GET_USER_INFO_UPDATE_RESPONSE = 'GET_USER_INFO_UPDATE_RESPONSE';

export const GET_EMAIL_CHANGE_RESPONSE = 'GET_EMAIL_CHANGE_RESPONSE';

export const GET_PASSWORD_CHANGE_RESPONSE = 'GET_PASSWORD_CHANGE_RESPONSE';
