export const GET_ADD_LINK_RESPONSE = 'GET_ADD_LINK_RESPONSE';

export const GET_DELETE_LINK_RESPONSE = 'GET_DELETE_LINK_RESPONSE';

export const GET_EDIT_LINK_RESPONSE = 'GET_EDIT_LINK_RESPONSE';

export const GET_REORDER_LINKS_RESPONSE = 'GET_REORDER_LINKS_RESPONSE';

export const GET_USER_INFO_UPDATE_RESPONSE = 'GET_USER_INFO_UPDATE_RESPONSE';

export const GET_EMAIL_CHANGE_RESPONSE = 'GET_EMAIL_CHANGE_RESPONSE';

export const GET_PASSWORD_CHANGE_RESPONSE = 'GET_PASSWORD_CHANGE_RESPONSE';

export const SET_LINK_UPDATED_REFERNCE_KEY = 'SET_LINK_UPDATED_REFERNCE_KEY';

export const SET_PORFILE_INFO_UPDATED_REFERNCE_KEY =
  'SET_PORFILE_INFO_UPDATED_REFERNCE_KEY';

export const GET_PROFILE_IMAGE_UPLOADED_RESPONSE =
  'GET_PROFILE_IMAGE_UPLOADED_RESPONSE';
