export const SET_SIGN_UP_RESPONSE = 'SET_SIGN_UP_RESPONSE';
export const GET_SIGN_UP_RESPONSE = 'GET_SIGN_UP_RESPONSE';

export const SET_OTP_MODAL_VISIBLE = 'SET_OTP_MODAL_VISIBLE';
export const GET_OTP_MODAL_VISIBLE = 'GET_OTP_MODAL_VISIBLE';

export const SET_SIGN_UP_RESPONSE_VERIFY = 'SET_SIGN_UP_RESPONSE_VERIFY';
export const GET_SIGN_UP_RESPONSE_VERIFY = 'GET_SIGN_UP_RESPONSE_VERIFY';

export const SET_SIGN_UP_EMAIL_RESPONSE = 'SET_SIGN_UP_EMAIL_RESPONSE';
export const GET_SIGN_UP_EMAIL_RESPONSE = 'GET_SIGN_UP_EMAIL_RESPONSE';

export const SET_OTP_VALIDATION = 'SET_OTP_VALIDATION';
export const GET_OTP_VALIDATION = 'GET_OTP_VALIDATION';

export const SET_EMAIL_VALIDATION = 'SET_EMAIL_VALIDATION';
export const GET_EMAIL_VALIDATION = 'GET_EMAIL_VALIDATION';

export const SET_REGISTER_RESPONSE = 'SET_REGISTER_RESPONSE';
export const GET_REGISTER_RESPONSE = 'GET_REGISTER_RESPONSE';

export const SET_PASSWORD_VALIDATION = 'SET_PASSWORD_VALIDATION';
export const GET_PASSWORD_VALIDATION = 'GET_PASSWORD_VALIDATION';
