export const SET_SIGN_UP_RESPONSE = 'SET_SIGN_UP_RESPONSE';
export const GET_SIGN_UP_RESPONSE = 'GET_SIGN_UP_RESPONSE';

export const SET_OTP_MODAL_VISIBLE = 'SET_OTP_MODAL_VISIBLE';
export const GET_OTP_MODAL_VISIBLE = 'GET_OTP_MODAL_VISIBLE';

export const SET_SIGN_UP_RESPONSE_VERIFY = 'SET_SIGN_UP_RESPONSE_VERIFY';
export const GET_SIGN_UP_RESPONSE_VERIFY = 'GET_SIGN_UP_RESPONSE_VERIFY';

export const SET_SIGN_UP_EMAIL_RESPONSE = 'SET_SIGN_UP_EMAIL_RESPONSE';
export const GET_SIGN_UP_EMAIL_RESPONSE = 'GET_SIGN_UP_EMAIL_RESPONSE';

export const SET_OTP_VALIDATION = 'SET_OTP_VALIDATION';
export const GET_OTP_VALIDATION = 'GET_OTP_VALIDATION';

export const SET_EMAIL_VALIDATION = 'SET_EMAIL_VALIDATION';
export const GET_EMAIL_VALIDATION = 'GET_EMAIL_VALIDATION';

export const SET_REGISTER_RESPONSE = 'SET_REGISTER_RESPONSE';
export const GET_REGISTER_RESPONSE = 'GET_REGISTER_RESPONSE';

export const SET_PASSWORD_VALIDATION = 'SET_PASSWORD_VALIDATION';
export const GET_PASSWORD_VALIDATION = 'GET_PASSWORD_VALIDATION';

export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN';

export const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN';
export const GET_REFRESH_TOKEN = 'GET_REFRESH_TOKEN';

export const SET_ADD_NAME_BIRTH_DATE_RESPONSE =
  'SET_ADD_NAME_BIRTH_DATE_RESPONSE';
export const GET_ADD_NAME_BIRTH_DATE_RESPONSE =
  'GET_ADD_NAME_BIRTH_DATE_RESPONSE';

export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';

export const SET_SUGGEST_USERS = 'SET_SUGGEST_USERS';
export const GET_SUGGEST_USERS = 'GET_SUGGEST_USERS';

export const SET_PASSWORD_CHANGE_REQUEST = 'SET_PASSWORD_CHANGE_REQUEST';
export const GET_PASSWORD_CHANGE_REQUEST = 'GET_PASSWORD_CHANGE_REQUEST';

export const SET_CHANGE_PASSWORD_RESPONSE = 'SET_CHANGE_PASSWORD_RESPONSE';
export const GET_CHANGE_PASSWORD_RESPONSE = 'GET_CHANGE_PASSWORD_RESPONSE';

export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST';
export const UNFOLLOW_USER_REQUEST = 'UNFOLLOW_USER_REQUEST';

export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS';
export const GET_LOGIN_STATUS = 'GET_LOGIN_STATUS';

export const SET_MOBILE_NUMBER_VALIDATION = 'SET_MOBILE_NUMBER_VALIDATION';
