export const SET_DEVICE_ID = 'SET_DEVICE_ID';
export const GET_DEVICE_ID = 'GET_DEVICE_ID';

export const SET_SIGN_UP_RESPONSE = 'SET_SIGN_UP_RESPONSE';
export const GET_SIGN_UP_RESPONSE = 'GET_SIGN_UP_RESPONSE';

export const SET_OTP_MODAL_VISIBLE = 'SET_OTP_MODAL_VISIBLE';
export const GET_OTP_MODAL_VISIBLE = 'GET_OTP_MODAL_VISIBLE';
